services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/amd64}
        TARGETARCH: ${TARGETARCH:-amd64}
    restart: always
    ports:
      - "9098:9098"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.5
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
