// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ensarkovankaya/go-notification-app/clients/webhook/models"
)

// SendMessageReader is a Reader for the SendMessage structure.
type SendMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendMessageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSendMessageOK creates a SendMessageOK with default headers values
func NewSendMessageOK() *SendMessageOK {
	return &SendMessageOK{}
}

/*
SendMessageOK describes a response with status code 200, with default header values.

Message received
*/
type SendMessageOK struct {
	Payload *models.MessageResult
}

// IsSuccess returns true when this send message o k response has a 2xx status code
func (o *SendMessageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this send message o k response has a 3xx status code
func (o *SendMessageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this send message o k response has a 4xx status code
func (o *SendMessageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this send message o k response has a 5xx status code
func (o *SendMessageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this send message o k response a status code equal to that given
func (o *SendMessageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the send message o k response
func (o *SendMessageOK) Code() int {
	return 200
}

func (o *SendMessageOK) Error() string {
	return fmt.Sprintf("[POST /{id}/][%d] sendMessageOK  %+v", 200, o.Payload)
}

func (o *SendMessageOK) String() string {
	return fmt.Sprintf("[POST /{id}/][%d] sendMessageOK  %+v", 200, o.Payload)
}

func (o *SendMessageOK) GetPayload() *models.MessageResult {
	return o.Payload
}

func (o *SendMessageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
