// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateMessageRequest create message request
//
// swagger:model CreateMessageRequest
type CreateMessageRequest struct {

	// message
	Message string `json:"message,omitempty"`

	// recipient
	Recipient string `json:"recipient,omitempty"`
}

// Validate validates this create message request
func (m *CreateMessageRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create message request based on context it is used
func (m *CreateMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMessageRequest) UnmarshalBinary(b []byte) error {
	var res CreateMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
