// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMessageRequest create message request
//
// swagger:model CreateMessageRequest
type CreateMessageRequest struct {

	// content
	// Required: true
	// Max Length: 2048
	// Min Length: 1
	Content *string `json:"content"`

	// recipient
	// Required: true
	// Max Length: 255
	// Min Length: 15
	Recipient *string `json:"recipient"`
}

// Validate validates this create message request
func (m *CreateMessageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecipient(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateMessageRequest) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("content", "body", m.Content); err != nil {
		return err
	}

	if err := validate.MinLength("content", "body", *m.Content, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("content", "body", *m.Content, 2048); err != nil {
		return err
	}

	return nil
}

func (m *CreateMessageRequest) validateRecipient(formats strfmt.Registry) error {

	if err := validate.Required("recipient", "body", m.Recipient); err != nil {
		return err
	}

	if err := validate.MinLength("recipient", "body", *m.Recipient, 15); err != nil {
		return err
	}

	if err := validate.MaxLength("recipient", "body", *m.Recipient, 255); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create message request based on context it is used
func (m *CreateMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMessageRequest) UnmarshalBinary(b []byte) error {
	var res CreateMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
